quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.smallrye-openapi.store-schema-directory=target/generated/swagger

game.bucket.name=game-images
quarkus.s3.devservices.enabled=true
quarkus.s3.devservices.buckets=game-images

# OIDC via Keycloak
quarkus.oidc.client-id=qui-est-ce-back
quarkus.oidc.application-type=service

# Dev Services: auto-provision Keycloak and import our realm
quarkus.keycloak.devservices.realm-path=realm-export.json
quarkus.keycloak.devservices.port=8180

